name: kanye_rest
description: A simple Flutter exemple on MVC arch and API connection as a demo project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  http: ^0.12.1
  connectivity: ^0.4.8+6
  mobx: ^1.2.0
  flutter_mobx: ^1.1.0
  share: ^0.6.4+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3
  build_runner: ^1.8.1

flutter:

  uses-material-design: true

  assets:
    - asset/image/0.jpg
    - asset/image/1.jpg
    - asset/image/2.jpg
    - asset/image/3.jpg
    - asset/image/4.jpg
    - asset/image/5.jpg
    - asset/image/6.jpg
    - asset/image/7.jpg